version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pillow flask
      - run:
          name: Run tests
          command: |
            python -m unittest discover -s src

  deploy-to-render:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Render
          command: |
            curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
              -H "Authorization: Bearer $RENDER_API_KEY"

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy-to-render:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
