version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install pillow flask
      - run:
          name: Run tests
          command: python -m unittest discover -s src
      - slack/notify:                           # <— aquí, dentro del mismo job
          channel: "${SLACK_CHANNEL}"
          event: fail                           # notificar si los tests fallan
          template: basic_fail_1

  deploy-to-render:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY"

  notify-slack-on-deploy-success:
    docker:
      - image: cimg/python:3.11
    steps:
      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: pass
          template: basic_success_1

workflows:
  version: 2
  build-test-deploy-and-notify:
    jobs:
      - build-and-test
      - deploy-to-render:
          requires:
            - build-and-test
      - notify-slack-on-deploy-success:
          requires:
            - deploy-to-render
