version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pillow
      - run:
          name: Run test
          command: |
            python -m unittest discover -s src 

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
