version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install pillow flask
      - run:
          name: Run tests
          command: python -m unittest discover -s src

  deploy-to-render:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Render
          command: |
            curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
              -H "Authorization: Bearer $RENDER_API_KEY"

  notify-slack-on-build-success:
    docker:
      - image: cimg/python:3.11
    steps:
      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: pass  # Notificar cuando la build pase
          template: basic_success_1

  notify-slack-on-deploy-success:
    docker:
      - image: cimg/python:3.11
    steps:
      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: pass  # Notificar cuando el deploy sea exitoso
          template: basic_success_1

  notify-slack-on-failure:
    docker:
      - image: cimg/python:3.11
    steps:
      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: fail  # Notificar cuando algo falle
          template: basic_fail_1

workflows:
  version: 2
  build-test-deploy-and-notify:
    jobs:
      - build-and-test
      - notify-slack-on-build-success:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - deploy-to-render:
          requires:
            - notify-slack-on-build-success  # Solo se ejecuta después de que la build pasa
          filters:
            branches:
              only: main
      - notify-slack-on-deploy-success:
          requires:
            - deploy-to-render  # Solo se ejecuta después del deploy exitoso
          filters:
            branches:
              only: main
      - notify-slack-on-failure:
          requires:
            - build-and-test  # Solo se ejecuta si la build falla
          filters:
            branches:
              only: main
