version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m unittest discover -s src

      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: fail
          template: basic_fail_1
          custom: '{"text":"¡Las *pruebas* han fallado! 🚨 Echa un vistazo a los logs."}'

      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: pass
          template: basic_success_1
          custom: '{"text":"¡Las *pruebas* han pasado! ✅ Todo listo para el siguiente paso."}'

  deploy-to-render:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Render
          command: |
            curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
              -H "Authorization: Bearer $RENDER_API_KEY"

  notify_slack_deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - slack/notify:
          channel: "${SLACK_CHANNEL}"
          event: pass
          template: basic_success_1
          custom: '{"text":"El *deploy* fue completado con éxito. :white_check_mark:"}'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy-to-render:
          requires:
            - build
          filters:
            branches:
              only: main
      - notify_slack_deploy:
          requires:
            - deploy-to-render
          filters:
            branches:
              only: main
